<h2 class="text-center">Seu contatos</h2>

<div class="table-responsive">
	<table class="table table-striped">
		<tr>
			<td>id</td>
			<td>Nome</td>
			<td>Celular</td>
			<td>Endereço</td>
			<td>Email</td>
		</tr>
		<!-- Exemplo de vizualização -->
		<!-- <tr>
			<td>1</td>
			<td>Carsio Eddyo</td>
			<td>991122410</td>
			<td>Rua Não sei o Nome</td>
			<td>carsio@iphoda.com</td>
		</tr> -->
		
		<?php foreach ($this->view->contatos as $contato): ?>
			<?php echo "<tr>"; ?>
				<?php echo "<td><input type ='checkbox' name = 'box". $contato['id'] ."' value ='". $contato['id'] ."'></input></td>"; ?>
				<?php echo "<td>". $contato['nome'] ."</td>"; ?>
				<?php echo "<td>". $contato['celular'] ."</td>"; ?>
				<?php echo "<td>". $contato['endereco'] ."</td>"; ?>
				<?php echo "<td>". $contato['email'] ."</td>"; ?>
			<?php echo "</tr>"; ?>
		<?php endforeach ?>


	</table>
</div>