<div class="row">
	<div class="col-md-6">
		<div class="btn-group">
			<button class="btn btn-default">
				<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
				Novo Contato
			</button>

			<button class="btn btn-default" onclick="location.href='http://agenda.com/contato';" id="myButton">
				<span class="glyphicon glyphicon-book" aria-hidden="true"></span>
				Contatos
			</button>
			<button class="btn btn-default">
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span>

				Perfil
			</button>
			<button class="btn btn-default">
				<span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
				Sobre
			</button>
		</div>
	</div>

	<div class="col-md-6">
		<!-- Single button -->
		<div class="btn-group">
			<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Action <span class="caret"></span>
			</button>
			<ul class="dropdown-menu">
				<li><a href="#">Action</a></li>
				<li><a href="#">Another action</a></li>
				<li><a href="#">Something else here</a></li>
				<li role="separator" class="divider"></li>
				<li><a href="#">Separated link</a></li>
			</ul>
		</div>

		<!-- Split button -->
		<div class="btn-group">
			<button type="button" class="btn btn-danger">Teste</button>
			<button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<span class="caret"></span>
				<span class="sr-only">Toggle Dropdown</span>
			</button>
			<ul class="dropdown-menu">
				<li><a href="#">Action</a></li>
				<li><a href="#">Another action</a></li>
				<li><a href="#">Something else here</a></li>
				<li role="separator" class="divider"></li>
				<li><a href="#">Separated link</a></li>
			</ul>
		</div>

	</div>
</div>

