<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2 class="text-center">Entrar</h2>
		<form class="col-sm-10 col-sm-offset-1" action="/autenticar" method="post">


			<div class="form-group">
				<label for="inputUser">Usuário</label>
				<input type="text" class="form-control" id="inputUser" placeholder="User" name="userEmail" <?php if(isset($this->view->email)) echo "value=".$this->view->email; ?>>
			</div>

			<div class="form-group">
				<label for="inputPass">Senha</label>
				<input type="password" class="form-control" id="inputPass" placeholder="Password" name="userPass">
			</div>

			<div class="form-group">
				<input type="submit" class="btn btn-primary form-control" value="Entrar">
			</div>
		</form>
	</div>
</div>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="alert alert-warning alert-dismissible" role="alert" id="msgLogar">
			<button id="closeMsg" type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			Logue-se para poder usar!
		</div>
	</div>
</div>

<script type="text/javascript">
	
	jQuery(document).ready(function($) {

		<?php 
			if (isset($this->view->email)) {
				echo "$('#inputPass').focus();";
			}

		 ?>
		
		$("#msgLogar").hide();

		<?php 
			if (isset($this->view->email)) {
				echo "$('#msgLogar').show();";
			}
		 ?>

		 $('#closeMsg').click(function(event) {
		 	$('#msgLogar').hide();
		 });
	});

</script>

<?php unset($this->view->email); ?>