<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2 class="text-center">Entrar</h2>
		<form class="col-sm-10 col-sm-offset-1" action="/autenticar" method="post">


			<div class="form-group">
				<label for="inputUser">Usuário</label>
				<input type="text" class="form-control" id="inputUser" placeholder="User" name="userEmail">
			</div>

			<div class="form-group">
				<label for="inputPass">Senha</label>
				<input type="password" class="form-control" id="inputPass" placeholder="Password" name="userPass">
			</div>

			<div class="form-group">
				<input type="submit" class="btn btn-primary form-control" value="Entrar">
			</div>
		</form>
	</div>
</div>